dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.1
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  audioplayers: ^5.2.1
  permission_handler: ^11.3.0
  flutter_foreground_task: ^6.1.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  device_info_plus: ^9.1.1
  battery_plus: ^5.0.2
  provider: ^6.1.1
  flutter_phone_state: ^0.6.4
