allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

// এই অংশটি phone_state সহ যেকোনো পুরনো প্লাগইনের নেমস্পেস অটো-ফিক্স করবে
subprojects { subproject ->
    subproject.afterEvaluate {
        if (subproject.hasProperty('android')) {
            subproject.android {
                if (namespace == null) {
                    namespace subproject.group
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
