allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    plugins.withId('com.android.application') {
        android {
            compileSdkVersion 35
        }
    }
    plugins.withId('com.android.library') {
        android {
            compileSdkVersion 35
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
