# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# JVM Memory allocation
org.gradle.jvmargs=-Xmx4608M -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android settings
android.nonTransitiveRClass=true
android.nonFinalResIds=false
