name: Build Flutter Release APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.x'

      - name: Enable AndroidX & Setup Properties
        run: |
          mkdir -p android
          cat << 'EOF' > android/gradle.properties
          org.gradle.jvmargs=-Xmx4608m
          android.useAndroidX=true
          android.enableJetifier=true
          EOF

      - name: Force Clean Leftover Plugin Registrant
        run: |
          find android/ -name "GeneratedPluginRegistrant.java" -exec rm -fv {} + || true

      - name: Clean Project & Get Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
